if __FILE__ == $0

  # TODO Generated stub
      @abbrev_to_region = {
'al' => 'alabama',
'ak' => 'alaska',
'az' => 'arizona',
'ar' => 'arkansas',
'ca' => 'california',
'co' => 'colorado',
'ct' => 'connecticut',
'dc' => 'district of columbia',
'de' => 'delaware',
'fl' => 'florida',
'ga' => 'georgia',
'hi' => 'hawaii',
'id' => 'idaho',
'il' => 'illinois',
'in' => 'indiana',
'ia' => 'iowa',
'ks' => 'kansas',
'ky' => 'kentucky',
'la' => 'louisiana',
'me' => 'maine',
'md' => 'maryland',
'ma' => 'massachusetts',
'mi' => 'michigan',
'mn' => 'minnesota',
'ms' => 'mississippi',
'mo' => 'missouri',
'mt' => 'montana',
'ne' => 'nebraska',
'nv' => 'nevada',
'nh' => 'new hampshire',
'nj' => 'new jersey',
'nm' => 'new mexico',
'ny' => 'new york',
'nc' => 'north carolina',
'nd' => 'north dakota',
'oh' => 'ohio',
'ok' => 'oklahoma',
'or' => 'oregon',
'pa' => 'pennsylvania',
'ri' => 'rhode island',
'sc' => 'south carolina',
'sd' => 'south dakota',
'tn' => 'tennessee',
'tx' => 'texas',
'ut' => 'utah',
'vt' => 'vermont',
'va' => 'virginia',
'wa' => 'washington',
'wv' => 'west virginia',
'wi' => 'wisconsin',
'wy' => 'wyoming' }

    @abbrev_to_country = {
'us'  => 'united states',
'usa'  => 'united states',
'uk'  => 'united kingdom',
'uae' => 'united arab emirates',
'au'  => 'australia'
}
end